import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "node:fs";
import path from "node:path";
import sveltePlugin from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const dir = prod ? "../slidesStudio-vault/.obsidian/plugins/slides-studio/" : "../testVault/.obsidian/plugins/slides-studio/";

// Helper to copy files and folders
function copyFiles() {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }

    const itemsToCopy = ["manifest.json", "styles.css", "pythonScripts", "slide-studio-app", "apps", "mediapipe_models"];
    
    for (const item of itemsToCopy) {
        if (fs.existsSync(item)) {
            const dest = path.join(dir, item);
            fs.cpSync(item, dest, { recursive: true, force: true });
            console.log(`Copied ${item} to ${dest}`);
        }
    }
}

// Plugin Build Context
const pluginContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["./src/main.ts"],
	bundle: true,
	platform: 'node',
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(dir, "main.js"),
	minify: prod,
});

// Editor Build Context
const editorContext = await esbuild.context({
    entryPoints: ["slide-studio-app/editor/src/main.js"],
    bundle: true,
    outfile: "slide-studio-app/editor/bundle.js",
    format: "esm",
    minify: prod,
    sourcemap: !prod,
    plugins: [
        sveltePlugin({
            preprocess: sveltePreprocess(),
            compilerOptions: { css: "injected" }
        })
    ],
    logLevel: "info",
});

if (prod) {
	await pluginContext.rebuild();
    await editorContext.rebuild();
    copyFiles();
	process.exit(0);
} else {
    // In dev mode, we watch both
    await pluginContext.watch();
    await editorContext.watch();
    copyFiles();
    
    // Watch slide-studio-app for changes to copy them
    fs.watch("slide-studio-app", { recursive: true }, (event, filename) => {
        if (filename && !filename.includes("bundle.js")) {
            copyFiles();
        }
    });
}
