import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "node:fs";
import path from "node:path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const dir = prod ? "../slidesStudio-vault/.obsidian/plugins/slides-studio/" : "../testVault/.obsidian/plugins/slides-studio/";

// Helper to copy files and folders
function copyFiles() {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }

    const itemsToCopy = ["manifest.json", "styles.css", "pythonScripts", "slide-studio-app", "mediapipe_models"];
    
    for (const item of itemsToCopy) {
        if (fs.existsSync(item)) {
            const dest = path.join(dir, item);
            fs.cpSync(item, dest, { recursive: true, force: true });
            console.log(`Copied ${item} to ${dest}`);
        }
    }
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["./src/main.ts"],
	bundle: true,
	platform: 'node',
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(dir, "main.js"),
	minify: prod,
});

if (prod) {
	await context.rebuild();
    copyFiles();
	process.exit(0);
} else {
    copyFiles();
	await context.watch();
}
